<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="4" errors="0" failures="1" skip="0"><testcase classname="sample.SampleTestSuite" name="test_data_driven_test_1" time="0.001"><failure type="exceptions.AssertionError" message="1 not greater than 1 : Argument didn't matched&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;selenium.webdriver.remote.remote_connection: DEBUG: POST http://127.0.0.1:56050/hub/session {&quot;sessionId&quot;: null, &quot;desiredCapabilities&quot;: {&quot;platform&quot;: &quot;ANY&quot;, &quot;browserName&quot;: &quot;firefox&quot;, &quot;version&quot;: &quot;&quot;, &quot;javascriptEnabled&quot;: true}}&#10;selenium.webdriver.remote.remote_connection: DEBUG: Finished Request&#10;selenium.webdriver.remote.remote_connection: DEBUG: POST http://127.0.0.1:56050/hub/session/405d4914-045f-f947-8730-3757b80ffbe6/timeouts/implicit_wait {&quot;sessionId&quot;: &quot;405d4914-045f-f947-8730-3757b80ffbe6&quot;, &quot;ms&quot;: 5000.0}&#10;selenium.webdriver.remote.remote_connection: DEBUG: Finished Request&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------"><![CDATA[  File "/usr/local/lib/python2.7/site-packages/unittest2/case.py", line 340, in run
    testMethod()
  File "/Users/farooque/PycharmProjects/crittercism/src/data_driven_test_wrapper.py", line 131, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/farooque/PycharmProjects/crittercism/tests/sample/sample.py", line 71, in test_data_driven_test
    self.assertGreater(value,1,"Argument didn't matched")
  File "/Users/farooque/PycharmProjects/crittercism/src/multiple_assertions.py", line 27, in wrapped
    assertion_method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/unittest2/case.py", line 941, in assertGreater
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Users/farooque/PycharmProjects/crittercism/src/multiple_assertions.py", line 27, in wrapped
    assertion_method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/unittest2/case.py", line 415, in fail
    raise self.failureException(msg)
'1 not greater than 1 : Argument didn\'t matched\n-------------------- >> begin captured logging << --------------------\nselenium.webdriver.remote.remote_connection: DEBUG: POST http://127.0.0.1:56050/hub/session {"sessionId": null, "desiredCapabilities": {"platform": "ANY", "browserName": "firefox", "version": "", "javascriptEnabled": true}}\nselenium.webdriver.remote.remote_connection: DEBUG: Finished Request\nselenium.webdriver.remote.remote_connection: DEBUG: POST http://127.0.0.1:56050/hub/session/405d4914-045f-f947-8730-3757b80ffbe6/timeouts/implicit_wait {"sessionId": "405d4914-045f-f947-8730-3757b80ffbe6", "ms": 5000.0}\nselenium.webdriver.remote.remote_connection: DEBUG: Finished Request\n--------------------- >> end captured logging << ---------------------']]></failure></testcase><testcase classname="sample.SampleTestSuite" name="test_data_driven_test_2" time="0.000"></testcase><testcase classname="sample.SampleTestSuite" name="test_data_driven_test_3" time="0.000"></testcase><testcase classname="sample.SampleTestSuite" name="test_data_driven_test_4" time="0.000"></testcase></testsuite>